### ISSUE TITLE
Reduzir a quantidade de arquivos nos modelos latex

### ISSUE THREAD

**Issue by ArthurGorgonio** [labican-ufrn/template-LaTeX#5]
A quantidade de arquivos nos modelos latex de tcc e estágio está praticamente no limite suportado pela nova versão do overleaf (overleaf V2), assim deve-se reduzir a quantidade de arquivos e pastas.

**Comment by tacianosilva** [comment]
Concordo! Está com muitas pastas e subsubsub arquivos. Acho que seções e subseções não precisão estarem em arquivos separados.
